/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stanislavin_msnger_JNIMsnger */

#ifndef _Included_com_stanislavin_msnger_JNIMsnger
#define _Included_com_stanislavin_msnger_JNIMsnger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stanislavin_msnger_JNIMsnger
 * Method:    sendMessage
 * Signature: ([C[CDD)V
 */
JNIEXPORT void JNICALL Java_com_stanislavin_msnger_JNIMsnger_sendMessage
  (JNIEnv *, jobject, jcharArray, jcharArray, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
